/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as NovidadesRouteImport } from './routes/novidades'
import { Route as GaleriaVideosRouteImport } from './routes/galeria-videos'
import { Route as GaleriaFotosRouteImport } from './routes/galeria-fotos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVideosRouteImport } from './routes/_authenticated/admin.videos'
import { Route as AuthenticatedAdminResultadosRouteImport } from './routes/_authenticated/admin.resultados'
import { Route as AuthenticatedAdminPatrocinadoresRouteImport } from './routes/_authenticated/admin.patrocinadores'
import { Route as AuthenticatedAdminNovidadesRouteImport } from './routes/_authenticated/admin.novidades'
import { Route as AuthenticatedAdminHomeRouteImport } from './routes/_authenticated/admin.home'
import { Route as AuthenticatedAdminGaleriaRouteImport } from './routes/_authenticated/admin.galeria'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as AuthenticatedAdminDocumentosRouteImport } from './routes/_authenticated/admin.documentos'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaVideosRoute = GaleriaVideosRouteImport.update({
  id: '/galeria-videos',
  path: '/galeria-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaFotosRoute = GaleriaFotosRouteImport.update({
  id: '/galeria-fotos',
  path: '/galeria-fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVideosRoute =
  AuthenticatedAdminVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResultadosRoute =
  AuthenticatedAdminResultadosRouteImport.update({
    id: '/resultados',
    path: '/resultados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPatrocinadoresRoute =
  AuthenticatedAdminPatrocinadoresRouteImport.update({
    id: '/patrocinadores',
    path: '/patrocinadores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNovidadesRoute =
  AuthenticatedAdminNovidadesRouteImport.update({
    id: '/novidades',
    path: '/novidades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomeRoute = AuthenticatedAdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGaleriaRoute =
  AuthenticatedAdminGaleriaRouteImport.update({
    id: '/galeria',
    path: '/galeria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/eventos',
    path: '/eventos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDocumentosRoute =
  AuthenticatedAdminDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/documentos': typeof DocumentosRoute
  '/eventos': typeof EventosRoute
  '/galeria-fotos': typeof GaleriaFotosRoute
  '/galeria-videos': typeof GaleriaVideosRoute
  '/novidades': typeof NovidadesRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/admin/home': typeof AuthenticatedAdminHomeRoute
  '/admin/novidades': typeof AuthenticatedAdminNovidadesRoute
  '/admin/patrocinadores': typeof AuthenticatedAdminPatrocinadoresRoute
  '/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/documentos': typeof DocumentosRoute
  '/eventos': typeof EventosRoute
  '/galeria-fotos': typeof GaleriaFotosRoute
  '/galeria-videos': typeof GaleriaVideosRoute
  '/novidades': typeof NovidadesRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/admin/home': typeof AuthenticatedAdminHomeRoute
  '/admin/novidades': typeof AuthenticatedAdminNovidadesRoute
  '/admin/patrocinadores': typeof AuthenticatedAdminPatrocinadoresRoute
  '/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/documentos': typeof DocumentosRoute
  '/eventos': typeof EventosRoute
  '/galeria-fotos': typeof GaleriaFotosRoute
  '/galeria-videos': typeof GaleriaVideosRoute
  '/novidades': typeof NovidadesRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/resultados': typeof ResultadosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/documentos': typeof AuthenticatedAdminDocumentosRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/galeria': typeof AuthenticatedAdminGaleriaRoute
  '/_authenticated/admin/home': typeof AuthenticatedAdminHomeRoute
  '/_authenticated/admin/novidades': typeof AuthenticatedAdminNovidadesRoute
  '/_authenticated/admin/patrocinadores': typeof AuthenticatedAdminPatrocinadoresRoute
  '/_authenticated/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/_authenticated/admin/videos': typeof AuthenticatedAdminVideosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/documentos'
    | '/eventos'
    | '/galeria-fotos'
    | '/galeria-videos'
    | '/novidades'
    | '/patrocinadores'
    | '/resultados'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin'
    | '/admin/documentos'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/galeria'
    | '/admin/home'
    | '/admin/novidades'
    | '/admin/patrocinadores'
    | '/admin/resultados'
    | '/admin/videos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/documentos'
    | '/eventos'
    | '/galeria-fotos'
    | '/galeria-videos'
    | '/novidades'
    | '/patrocinadores'
    | '/resultados'
    | '/sitemap.xml'
    | '/sobre'
    | '/admin/documentos'
    | '/admin/equipe'
    | '/admin/eventos'
    | '/admin/galeria'
    | '/admin/home'
    | '/admin/novidades'
    | '/admin/patrocinadores'
    | '/admin/resultados'
    | '/admin/videos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/documentos'
    | '/eventos'
    | '/galeria-fotos'
    | '/galeria-videos'
    | '/novidades'
    | '/patrocinadores'
    | '/resultados'
    | '/sitemap.xml'
    | '/sobre'
    | '/_authenticated/admin'
    | '/_authenticated/admin/documentos'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/galeria'
    | '/_authenticated/admin/home'
    | '/_authenticated/admin/novidades'
    | '/_authenticated/admin/patrocinadores'
    | '/_authenticated/admin/resultados'
    | '/_authenticated/admin/videos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  DocumentosRoute: typeof DocumentosRoute
  EventosRoute: typeof EventosRoute
  GaleriaFotosRoute: typeof GaleriaFotosRoute
  GaleriaVideosRoute: typeof GaleriaVideosRoute
  NovidadesRoute: typeof NovidadesRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  ResultadosRoute: typeof ResultadosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novidades': {
      id: '/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof NovidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria-videos': {
      id: '/galeria-videos'
      path: '/galeria-videos'
      fullPath: '/galeria-videos'
      preLoaderRoute: typeof GaleriaVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria-fotos': {
      id: '/galeria-fotos'
      path: '/galeria-fotos'
      fullPath: '/galeria-fotos'
      preLoaderRoute: typeof GaleriaFotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/videos': {
      id: '/_authenticated/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AuthenticatedAdminVideosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resultados': {
      id: '/_authenticated/admin/resultados'
      path: '/resultados'
      fullPath: '/admin/resultados'
      preLoaderRoute: typeof AuthenticatedAdminResultadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/patrocinadores': {
      id: '/_authenticated/admin/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/admin/patrocinadores'
      preLoaderRoute: typeof AuthenticatedAdminPatrocinadoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/novidades': {
      id: '/_authenticated/admin/novidades'
      path: '/novidades'
      fullPath: '/admin/novidades'
      preLoaderRoute: typeof AuthenticatedAdminNovidadesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/home': {
      id: '/_authenticated/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AuthenticatedAdminHomeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/galeria': {
      id: '/_authenticated/admin/galeria'
      path: '/galeria'
      fullPath: '/admin/galeria'
      preLoaderRoute: typeof AuthenticatedAdminGaleriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/documentos': {
      id: '/_authenticated/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AuthenticatedAdminDocumentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDocumentosRoute: typeof AuthenticatedAdminDocumentosRoute
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminGaleriaRoute: typeof AuthenticatedAdminGaleriaRoute
  AuthenticatedAdminHomeRoute: typeof AuthenticatedAdminHomeRoute
  AuthenticatedAdminNovidadesRoute: typeof AuthenticatedAdminNovidadesRoute
  AuthenticatedAdminPatrocinadoresRoute: typeof AuthenticatedAdminPatrocinadoresRoute
  AuthenticatedAdminResultadosRoute: typeof AuthenticatedAdminResultadosRoute
  AuthenticatedAdminVideosRoute: typeof AuthenticatedAdminVideosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDocumentosRoute: AuthenticatedAdminDocumentosRoute,
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminGaleriaRoute: AuthenticatedAdminGaleriaRoute,
  AuthenticatedAdminHomeRoute: AuthenticatedAdminHomeRoute,
  AuthenticatedAdminNovidadesRoute: AuthenticatedAdminNovidadesRoute,
  AuthenticatedAdminPatrocinadoresRoute: AuthenticatedAdminPatrocinadoresRoute,
  AuthenticatedAdminResultadosRoute: AuthenticatedAdminResultadosRoute,
  AuthenticatedAdminVideosRoute: AuthenticatedAdminVideosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  DocumentosRoute: DocumentosRoute,
  EventosRoute: EventosRoute,
  GaleriaFotosRoute: GaleriaFotosRoute,
  GaleriaVideosRoute: GaleriaVideosRoute,
  NovidadesRoute: NovidadesRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  ResultadosRoute: ResultadosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
