// This file is automatically generated. Do not edit it directly.
/*
  Cabeçalho (pt-BR):
  Arquivo responsável por um middleware de autenticação com Supabase.
  - Verifica variáveis de ambiente necessárias.
  - Lê o cabeçalho Authorization da requisição (Bearer token).
  - Instancia um cliente Supabase limitado ao token recebido.
  - Valida as claims do token e expõe supabase + userId + claims no contexto.
  Uso: destinado a proteger rotas/handlers que exigem autenticação.
*/

import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



// Middleware que exige autenticação via Supabase. Retorna um middleware do lado server.
export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    // Recupera variáveis de ambiente necessárias para conectar ao Supabase
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    // Verifica se as variáveis de ambiente estão presentes
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      // Mensagem de erro amigável indicando quais variáveis estão faltando
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    // Obtém o objeto Request atual fornecido pelo framework
    const request = getRequest();

    // Valida que o request e seus headers estejam disponíveis
    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    // Lê o cabeçalho Authorization
    const authHeader = request.headers.get('authorization');

    // Se não houver cabeçalho Authorization, rejeita a requisição
    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    // Só suporta esquema Bearer
    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    // Extrai o token do cabeçalho "Bearer <token>"
    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    // Cria um cliente Supabase usando o token do usuário para requisições autenticadas.
    // Observações:
    // - Não usa armazenamento local (storage: undefined) pois estamos no servidor.
    // - Não persiste sessão nem tenta refresh automático aqui.
    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Valida o token obtendo as claims (informações do usuário) do Supabase
    const { data, error } = await supabase.auth.getClaims(token);
    // Se ocorrer erro ou não houver claims, considera o token inválido
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    // Garante que haja um user ID (sub) nas claims
    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    // Passa para o próximo middleware/handler incluindo no contexto:
    // - o cliente supabase autenticado
    // - userId extraído das claims
    // - todas as claims do token
    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
