/*
  Arquivo: auth-attacher.ts

  Propósito:
  - Middleware do lado do cliente que anexa o token de autenticação (Bearer) fornecido
    pelo Supabase às chamadas de RPC/Server Functions feitas via @tanstack/react-start.
  - Deve ser registrado globalmente como functionMiddleware para que o navegador
    envie o header Authorization nas requisições de funções do servidor.

  Observações para desenvolvedores iniciantes:
  - Este arquivo apenas lê a sessão atual do Supabase no cliente e, se existir
    um access_token, adiciona o header Authorization nas próximas chamadas.
  - Não altera lógica de autenticação, apenas encaminha o token nas requisições.
*/

/* This file is automatically generated. Do not edit it directly. */
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // Pega a sessão atual do Supabase no cliente
    const { data } = await supabase.auth.getSession()
    // Extrai o access_token da sessão (se existir)
    const token = data.session?.access_token
    // Chamamos next() passando headers; se houver token, adicionamos Authorization
    // Isso faz com que as chamadas de Server Function incluam o Bearer token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
