/*
  Arquivo: client.server.ts
  Propósito: Criar e exportar um cliente Supabase para uso no lado do servidor com a Service Role Key.
  Observações:
  - Este cliente possui privilégios elevados (bypassa RLS) e só deve ser usado em rotinas confiáveis do servidor
    como rotinas de administração, funções server-side ou rotas do servidor.
  - Não expor este cliente ao navegador / cliente.
  - Comentários adicionais no código explicam o que cada bloco faz e por que é necessário.
*/

// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/* 
  Cria um cliente Supabase configurado com a Service Role Key (chave de serviço).
  O cliente resultante deve ser usado apenas em código de servidor confiável,
  pois a Service Role Key ignora Row Level Security (RLS).
*/
function createSupabaseAdminClient() {
  // Lê as variáveis de ambiente necessárias para inicializar o cliente
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  /* 
    Validação das variáveis de ambiente:
    - Se alguma estiver ausente, logamos um erro e lançamos uma exceção para evitar
      inicialização silenciosa com configurações inválidas.
    - Mensagem aponta como adicionar as chaves no .env (documentação local).
  */
  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Crie o arquivo .env na raiz do projeto com as chaves do seu projeto Supabase (veja COMO-RODAR.md).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  /* 
    Cria o cliente Supabase tipado com Database.
    Configura o auth para ambiente server-side:
    - storage: undefined (sem localStorage no servidor)
    - persistSession: false (não persistir sessão no servidor)
    - autoRefreshToken: false (não tentar renovar tokens automaticamente)
    Essas opções evitam comportamentos pensados para cliente/browser.
  */
  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

/* 
  Cache do cliente admin: inicialização preguiçosa (lazy).
  - Mantemos a instância para reutilizar conexões e evitar recriações.
  - Inicializada apenas quando necessária.
*/
let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  /* 
    Proxy que intercepta acessos às propriedades do cliente.
    - No primeiro acesso, inicializa o cliente via createSupabaseAdminClient.
    - Depois delega todas as chamadas para a instância real.
    Isso permite importar o módulo no topo sem criar imediatamente a conexão.
  */
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
