/*
  Arquivo: client.ts

  Propósito:
  - Fornece um cliente Supabase configurado para uso na aplicação AGNEP.
  - Centraliza a criação e inicialização do cliente Supabase, tratando a leitura
    das variáveis de ambiente tanto no cliente (Vite) quanto no servidor (SSR).
  - Exporta o objeto `supabase` como um proxy para inicializar o cliente sob demanda
    (lazy initialization), evitando criar a instância até que seja realmente usada.

  Observações:
  - Não altere a lógica deste arquivo diretamente se for gerado automaticamente.
  - Comentários adicionais explicam partes importantes para desenvolvedores iniciantes.
*/

/* This file is automatically generated. Do not edit it directly. */
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/* Cria e configura uma instância do cliente Supabase.
   O motivo de ter essa função é isolar a lógica de leitura de variáveis de ambiente
   e as opções de autenticação (storage, refresh automático, persistência de sessão).
*/
function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  // Lemos as variáveis de ambiente primeiro pelo import.meta.env (quando rodando no cliente com Vite)
  // e em seguida por process.env para suportar renderização no servidor.
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  // Se alguma variável obrigatória estiver faltando, avisamos e lançamos um erro.
  // Isso evita tentativas silenciosas de usar o Supabase sem configuração adequada.
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Falta(m) variável(is) de ambiente do Supabase: ${missing.join(', ')}. Crie o arquivo .env na raiz do projeto com as chaves do seu projeto Supabase (veja COMO-RODAR.md).`;
    // Logamos o erro para facilitar o debugging durante o desenvolvimento.
    console.error(`[Supabase] ${message}`);
    // Lançamos um erro para impedir que a aplicação continue sem as variáveis necessárias.
    throw new Error(message);
  }

  // Criamos o cliente Supabase tipado com a interface Database.
  // As opções de auth:
  // - storage: usamos localStorage no browser para persistir sessão; undefined no SSR.
  // - persistSession: mantém a sessão entre reloads.
  // - autoRefreshToken: renova o token automaticamente quando possível.
  // - flowType: 'pkce' usa fragmento (#) na URL para os links de recuperação/redefinição
  //   de senha do Supabase funcionarem em aplicações de página única (SPA sem SSR),
  //   evitando erros de "otp_expired" / "access_denied" ao abrir o link do e-mail
  //   em http://localhost:5173
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      flowType: 'pkce',
    }
  });
}

/* Variável interna para armazenar a instância criada do Supabase.
   Inicialmente undefined; será populada na primeira utilização (lazy initialization).
*/
let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/* Exportamos `supabase` como um Proxy que delega as operações para a instância real.
   Razões para usar um proxy:
   - Permite criação tardia (lazy) do cliente apenas quando uma propriedade/método for acessado.
   - Evita problemas de ordem de importação ou inicialização em ambientes SSR/CSR.
   O proxy intercepta `get` e, se necessário, cria a instância chamando createSupabaseClient().
*/
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
